version: "3.3"

services:

  nginx_from_step_images:
    image: harsonosuwaji/nginx-advantage:latest
    restart: unless-stopped
    tty: true
    container_name: nginx_from_step_images
    ports:
      - "8080:80"
    networks:
      - proxy

networks:
  proxy: {}